image: mcr.microsoft.com/playwright:latest

stages:
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: test
  script:
    - npm install
  only:
    - master

run_tests_prod:
  stage: test
  variables:
    SECURE_FILES_DOWNLOAD_PATH: 'src'
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - npm run test:prod
  artifacts:
    paths:
      - test-results/
    expire_in: 1 week

run_tests_dev:
  stage: test
  variables: 
    SECURE_FILES_DOWNLOAD_PATH: 'src'
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - npm run test:dev
  artifacts:
    paths:
      - test-results/
    expire_in: 1 week
