stages:
  - test

run_tests_dev:
  stage: test
  image: mcr.microsoft.com/playwright:v1.38.0-jammy
  variables: 
    SECURE_FILES_DOWNLOAD_PATH: 'src'
  script:
    - npm install -D @playwright/test
    - npm ci
    - npm run test:dev
  artifacts:
    paths:
      - ./playwright-report/
      - ./Screenshot/
    when: always
    expire_in: 4 days

  
