stages:
  - test

run_tests_dev:
  stage: test
  image: mcr.microsoft.com/playwright:v1.41.2-jammy 
  variables: 
    SECURE_FILES_DOWNLOAD_PATH: '.'
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - npm install -D @playwright/test
    - npm ci
    - npm run all
  artifacts:
    paths:
      - ./playwright-report/
      - ./Screenshot/
    when: always
    expire_in: 4 days
