stages:
  - install
  - build
  - deploy
  - e2e

test_e2e:
  stage: e2e
  allow_failure: false
  image: mcr.microsoft.com/playwright:focal
  before_script:
    - cd playwright
    - npm i
    - npx playwright install
  script:
    - npm run test:dev
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'failed' ]; then
        echo "At least one test suite has failed, returning"
        echo "Go check test results here:"
        echo "$CI_JOB_URL/artifacts/file/playwright/out/report/index.html"
      fi
  cache:
    key: ${CI_COMMIT_REF_SLUG}-e2e
    paths:
      - playwright/node_modules
  artifacts:
    paths:
      - playwright/out/report/
    when: on_failure
    reports:
      junit: playwright/out/report/report.xml
